eos:
  online_inverter_enabled: true
  path: /home/cplumber/test_chain/tables
  preinverted_eos_path: default
  type: table
hydro:
  baryon_charge_enabled: true
  electric_charge_enabled: true
  strange_charge_enabled: true
  viscous_parameters:
    bulk:
      constant_zeta_over_s: 0.0
      cs2_dependent_zeta_A: 1.67552
      cs2_dependent_zeta_p: 2.0
      mode: constant
      modulate_with_tanh: false
      relaxation_mode: default
    shear:
      constant_eta_over_s: 0.16
      mode: constant
      relaxation_mode: default

initial_conditions:
  coordinate_system: hyperbolic
  dimension: 2
  file: /home/cplumber/test_chain/models/CCAKE/initial_conditions/ccake_trento.dat
  input_as_entropy: false
  t0: 0.6
  type: ccake
output:
  calculate_observables: false
  hdf_evolution: false
  print_conservation_state: true
  txt_evolution: true
  check_causality: true
parameters:
  buffer_particles:
    circular: false
    enabled: false
    padding_thickness: 0.1
  dt: 0.05
  energy_cutoff: 0.15
  h_T: 0.3
  h_eta: 0.5
  kernel_type: cubic_spline
  max_tau: 30.0
  rk_order: 2
particlization:
  T: 150
  enabled: true
  type: fixed_T
