---
eos:
  online_inverter_enabled: false
  path: /u/surkhab2/CCAKE/build/EoS/Houston
  preinverted_eos_path: /u/surkhab2/CCAKE/build/inverted_eos.h5
  type: table
hydro:
  baryon_charge_enabled: false
  electric_charge_enabled: false
  strange_charge_enabled: false
  viscous_parameters:
    bulk:
      constant_zeta_over_s: 0.0
      cs2_dependent_zeta_A: 1.67552
      cs2_dependent_zeta_p: 2.0
      mode: constant
      modulate_with_tanh: false
      relaxation_mode: default
    shear:
      constant_eta_over_s: 0.0
      mode: disabled
      relaxation_mode: default
initial_conditions:
  coordinate_system: hyperbolic
  dimension: 3
  file: /u/surkhab2/AMPTGenesis/ics/ics_19p6/x_p1_eta_p13.dat
  input_as_entropy: false
  t0: 1.0
  type: ccake
output:
  calculate_observables: true
  hdf_evolution: false
  print_conservation_state: true
  txt_evolution: false
parameters:
  buffer_particles:
    circular: false
    enabled: false
    padding_thickness: 0.1
  dt: 0.05
  energy_cutoff: 0.15
  h_T: 0.2
  h_eta: 0.2
  kernel_type: cubic_spline
  max_tau: 30.0
  rk_order: 2
particlization:
  T: 150.0
  enabled: true
  type: fixed_T

